// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebHocCSDL.Data;

#nullable disable

namespace WebHocCSDL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250309133556_MakeRelationshipsJsonNullable")]
    partial class MakeRelationshipsJsonNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebHocCSDL.Models.DatabaseDesign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConceptualDesign")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERD")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogicalDesign")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhysicalDesign")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequirementDescription")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Designs");
                });

            modelBuilder.Entity("WebHocCSDL.Models.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Attributes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DatabaseDesignId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseDesignId");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("WebHocCSDL.Models.Relationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DatabaseDesignId")
                        .HasColumnType("int");

                    b.Property<string>("Entity1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Entity2")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseDesignId");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("WebHocCSDL.Models.Entity", b =>
                {
                    b.HasOne("WebHocCSDL.Models.DatabaseDesign", "DatabaseDesign")
                        .WithMany("Entities")
                        .HasForeignKey("DatabaseDesignId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DatabaseDesign");
                });

            modelBuilder.Entity("WebHocCSDL.Models.Relationship", b =>
                {
                    b.HasOne("WebHocCSDL.Models.DatabaseDesign", "DatabaseDesign")
                        .WithMany("Relationships")
                        .HasForeignKey("DatabaseDesignId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DatabaseDesign");
                });

            modelBuilder.Entity("WebHocCSDL.Models.DatabaseDesign", b =>
                {
                    b.Navigation("Entities");

                    b.Navigation("Relationships");
                });
#pragma warning restore 612, 618
        }
    }
}
